#!/usr/bin/with-contenv /bin/bash

echo "ssh_user::"$SSH_USER >> /variables
echo "ssh_pass::"$SSH_PASS >> /variables
echo "db_user"::"$DB_USER" >> /variables
echo "db_name"::"$DB_NAME" >> /variables
echo "db_name"::"$DB_PASS" >> /variables
echo "db_host"::"$DB_HOST" >> /variables
echo "wp_cli::"$WP_CLI >> /variables
chmod 600 /variables

sed -i "s/nginx:x:101:102:nginx:\/var\/lib\/nginx:\/sbin\/nologin/$SSH_USER:x:100:101:nginx:\/DATA:\/bin\/bash/g" /etc/passwd
sed -i "s/nginx:x:101:102:nginx:\/var\/lib\/nginx:\/sbin\/nologin/$SSH_USER:x:100:101:nginx:\/DATA:\/bin\/bash/g" /etc/passwd-

sed -i "s/demouser/$SSH_USER/g" /etc/php7/php-fpm.conf
sed -i "s/demouser/$SSH_USER/g" /etc/nginx/nginx.conf
