#!/usr/bin/with-contenv /bin/bash

if [ ! -d /DATA/htdocs ] ; then
  mkdir -p /DATA/htdocs
  chown $SSH_USER:www-data /DATA/htdocs
fi



if [ ! -d /DATA/logs/nginx ] ; then
  mkdir -p /DATA/logs/nginx
  chown $SSH_USER:nginx /DATA/logs/nginx
fi

if [ ! -d /tmp/nginx ] ; then
  mkdir -p /tmp/nginx
  chown $SSH_USER:nginx /tmp/nginx
fi
